### ISSUE TITLE
update permapeople.org data

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#102]
Seems to be a database superior to practicalplants:

https://permapeople.org/knowledgebase/api-docs.html

Following columns would be very interesting for us:

- Nutrition Demand
 - Edible (true/false)
 - Edible parts (list)
 - Edible uses (e.g. oil)
 - Spacing
 - Germination time
 - Seed planting depth
 - Days to harvest (probably Days till harvest is meant?)
 - When to sow (indoors)
 - When to sow (outdoors)
 - Seed viability

Other columns should be included if possible. Excluded columns should be documented for further investigations.

__*EDIT from Nursultan on 09.04.2023:*__

- [x] timeout between requests

**Comment by aidnurs** [comment]
# Notes
State: TBD

**This is not finished research, please don't comment it yet**

- > Currently, the data consists of user contributions with an additional import of [Plants for a Future data](https://pfaf.org/) and Wikipedia Images.
- > What is the license of the database?
If not stated otherwise, everything in the database and related content is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/). Please reach out to [hello@permapeople.org](mailto:hello@permapeople.org) if you have different requirements.
- They claim to have 10k entries, in comparison PermaplanT have 6k
- Terms and definitions i.e. glossary https://permapeople.org/knowledgebase/terms-and-definitions.html

**Comment by benben** [comment]
As for the companion/anatagonist info: Yes this was done mainly be me and our users :) hi!

**Comment by markus2330** [comment]
@aidnurs @badnames Can you create accounts at permapeople.org so that you can get an API key?

**Comment by aidnurs** [comment]
> @aidnurs @badnames Can you create accounts at permapeople.org so that you can get an API key?

I've already created one while I was reviewing their project

**Comment by markus2330** [comment]
We got API keys but no CSV so far. So the first task would be to download everything into our CSV, so that we can investigate the data.

**Comment by aidnurs** [comment]
Hey @benben,

thank you for the API keys, I was able to fetch all the plants from the database once. However, after the first fetch, I get `503 Service Temporarily Unavailable` back for every request that I make now. Could you please advise us if you have any API limitations or if it is a temporary state?

Thank you very much in advance!
Nursultan

**Comment by markus2330** [comment]
It looks like their whole site is down, so the API issue you have is probably unrelated to what you fetched before.

Anyway, I think we need to implement incremental fetches (only of changes), so that we can fetch changes every few minutes. This is needed as we want to directly edit permapeople.org plant database and the user then wants to see the updates relatively quickly.

As permapeople.org is a wiki, there should be a way to list the recently edited files?

**Comment by benben** [comment]
I suggest you keep it gentle and do not hit the API with more than 1 concurrent request per second.

It is not a wiki but we have a history. We could make the last updated at field of plants available and sortable/filterable in the API so you can use that to keep requests to a minimum.

**Comment by markus2330** [comment]
> We could make the last updated at field of plants available and sortable/filterable in the API so you can use that to keep requests to a minimum.

Yes, that would be amazing! Then we could have updates every few minutes, with a minimum number of requests.

**Comment by aidnurs** [comment]
Hey @benben,

thank you once again for the access to your API, the unified data looks sharp!

As we're currently syncing and trying to merge the datasets, I have a question regarding the types of the following columns delivered from your API:

- [ ] germination_time: make range of days
- [ ] seed_viability: make range of years
- [ ] spacing: convert everything to cm
- [ ] germination_temperature: convert to ranges of °C.
- [ ] days_to_harvest: format should be numeric (instead of 90days).
- [ ] seed_planting_depth: format should be cm, please convert
- [ ] cold_stratification_temperature: convert to ranges of °C.

We would like to define boundaries and types in our database for certain columns merging the datasets. However, upon reviewing the data, it appears that these boundaries have not been set for the list above as they may contain different value formats e.g. `1 week`, `12 days`, `2-3 years`, `3 to 5 years`, etc.

Given that we would probably synchronize our data from time to time, it may be useful to establish transformation rules on our side. For the columns such as "sun" and "water" it was obvious and clear for us how to proceed with transformation. Could you please advise us on the rest of the columns listed above:
1. do they have an inner type in your database or they're just strings?
2. is it up for a user to fill them out or do you still correct the values afterward?

We believe that the uniform datasets including the strictly defined types would make the data even better to maintain in the future, however, we're always up for suggestions, so feel free to share your opinion on that! Maybe we oversee some considerations here and it would be better to leave these columns as custom strings providing freedom to the end users.

@markus2330 maybe you have any additional questions regarding the types?

Thank you very much for your assistance, Benjamin!

Sincerely,
Nursultan

**Comment by markus2330** [comment]
Seems like there is no response, so we need to manually fix these problems.

**Comment by benben** [comment]
All fields you described are just plain strings, we do not transform anything when showing on the website or through the API. Permapeople is a crowd-sourced (much like Wikipedia) project, where everyone can contribute. If you find errors or fuzzy data, feel free to fix them. For example converting `1 week` to `7 days` so everything just shows the days. I'd not remove the units completely because it is much more easy to consume reading `5cm` than `5` but everything is up for discussion.

Are there any specific transformations you wanna do?

**Comment by markus2330** [comment]
We already have most transformations we need when importing data but it is becoming a bottomless pit for some fields, e.g. spacing doesn't have much data but is so inconsistent that we cannot use it. There we would need clear cm per row and distance per row information.

Imho guidelines are needed that describe wanted content. I heard (quite some time ago) MusicBrainz is doing an excellent job in that regards.

**Comment by benben** [comment]
There are roughly ~120 plants with spacing, most of them have their spacing in cm. I guess it would be the quickest, to (semi)manually fix the few which do not show cm.

Also there is no single correct value, all data is more or less a suggestion for the gardener to start their own experiments.

**Comment by benben** [comment]
Also, I think it would be best if you could join our discord here https://discord.gg/t6PP5BsJR2 We have a channel for these exact topics :)

**Comment by markus2330** [comment]
> There are roughly ~120 plants with spacing, most of them have their spacing in cm. I guess it would be the quickest, to (semi)manually fix the few which do not show cm.

The problem is that it is unclear what the correct fix is. cm/inch is the easiest thing, the larger problem is how to interpret the number(s). Is a single number the distance from plant to plant? Or the space between the rows or the plants? With two numbers there are even more ways of interpretations.

> Also there is no single correct value, all data is more or less a suggestion for the gardener to start their own experiments.

Of course. But I would like to interpret the numbers as they were intended to be interpreted and without any schema/description this only works in very simple cases. Even for mature_size_width/height you already have problems, e.g., is it average, minimum/maximum typical, exceptional small/big cases? I don't think that specification by column names can work good enough for use in apps, even for vague data like in this case :wink: 

> Also, I think it would be best if you could join our discord here https://discord.gg/t6PP5BsJR2 We have a channel for these exact topics :)

Sorry I don't use Discord and it is non-free so I prefer not to use it (a bit ironic to write this in another non-free system). In PermaplanT we use Nextcloud as our chat, you are invited if you are interested.

Anyway, as far as I understood we are the only ones that want to interpret the data within an app, so we also have different requirements. So the issue here seems like the right place to discuss this.

Do you know if PFAF maybe already has descriptions how to interpret these numbers/enums? Most of the data is very consistent, so they must have some convention or schema.

**Comment by benben** [comment]
> The problem is that it is unclear what the correct fix is. cm/inch is the easiest thing, the larger problem is how to interpret the number(s). Is a single number the distance from plant to plant? Or the space between the rows or the plants? With two numbers there are even more ways of interpretations.

One number means it is spacing between plants and rows. Two numbers means first is spacing between plants, second between rows. This is a common convention in gardening circles.

> Even for mature_size_width/height you already have problems, e.g., is it average, minimum/maximum typical, exceptional small/big cases? I don't think that specification by column names can work good enough for use in apps, even for vague data like in this case 😉

I don't understand this. There is not a single correct metric in gardening. All numbers are point of references for guiding your decision. Gardening just doesn't work like that. As I said a couple of times: to build a useful gardening app, correctness does not matter that much. No one plants a tree and comes back to you in 20 years saying: But your app said it will be 10 meters, now it is just 9 meters! Your app is trash!

> Sorry I don't use Discord and it is non-free so I prefer not to use it (a bit ironic to write this in another non-free system). In PermaplanT we use Nextcloud as our chat, you are invited if you are interested.

I prefer discussing this inside the permapeople community.

> Do you know if PFAF maybe already has descriptions how to interpret these numbers/enums? Most of the data is very consistent, so they must have some convention or schema.

You should definitely work more with our data and PFAF data. PFAF doesn't have annuals, so no spacing data  or planting data at all. For heights they mostly just say one single number, which is fine for everyone I know growing trees.

**Comment by benben** [comment]
Just a small update: You can now list plants through the API based on a new GET param `updated_since`, see [here](https://permapeople.org/knowledgebase/api-docs.html#list-plants)

Also I want to remind you about our license, which needs appropriate credit and sharing under the same license. I recommend [reading this](https://creativecommons.org/licenses/by-sa/4.0/). We also added a [data acknowlegement page](https://permapeople.org/knowledgebase/data-acknowledgement.html) to make our point of view on data sharing more clear. 

Let us know how it goes and if you need anything. Thanks!

**Comment by markus2330** [comment]
will work on this later
