### ISSUE TITLE
Migration to Vite 5 and Vitest

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#1115]
We are currently using Jest as a unit test runner.
This is suboptimal since Jest only supports CJS modules.
The JS community is shifting towards the use of ESM which is already supported natively by Vite.
This is evident by the fact that ESM is the standard since ES6, more and more packages adopt EMS and even NodeJS, which invented the CJS module system understands ESM now.

Vitest is a new testing framework that supports all the same functionality as Jest. It recently was released as stable version 1.0.0. 
Using Vitest in comparison to Jest enables us to have one config for both Vite and Vitest: `vite.config.ts`.
Vitest works hand in hand with Vite.

Additionally we can use packages like MSW that do not work properly with Jest.
One more point is we can remove some config files, and `__mocks__` folders:
- `jest.config.js`: not needed, because we would be using Vitest
- `babel.config.js`: not needed, because we needed that for Jest to understand our ESM syntax code.
- `svg-transform.ts`: not needed, Vite plugins work for Vitest aswell ;)
- `src/__mocks__/svg.ts`: not needed, the above Vite plugin handles this.
- `config/__mocks__/env.ts`: not needed, Vitest understands the `import.meta` syntax
- `config/axios/__mocks__/index.ts`: would be replaced by a more elaborate MSW setup

Edit: This would go hand in hand with an upgrade to Node 20 and Vite 5, since that is what Vitest needs.

**Comment by Bushuo** [comment]
@ElektraInitiative/permaplant 
Does anyone else have experience with this? Every comment is appreciated.

**Comment by markus2330** [comment]
Thanks for the detailed analysis!

@absurd-turtle and @badnames wanted to do something similar to finish #1038.

**Comment by Bushuo** [comment]
@markus2330 Thanks, I will compare their approach. I have a working setup in a local branch already.

**Comment by markus2330** [comment]
> Thanks, I will compare their approach.

I am not sure if their approach is only an idea or already implemented in the branch.

> I have a working setup in a local branch already.

How should we proceed here? Should we use your approach? Can you push what you currently have?

**Comment by absurd-turtle** [comment]
@markus2330 @Bushuo Yes, we already migrated to vitest in the branch mentioned above.
We had trouble with the current test setup so we decided it would be a good idea to switch to vitest since it makes sense to have the test-setup use the same config and build system as you mentioned above.
It wasn't really obvious from the branch I have to admit. We only mentioned the changes in the meeting.
All of the current tests are up and running again on that branch.
It's nice that you pointed out the files that we can remove because we weren't so informed on that regard.
We are still having trouble setting up the snapshot tests, which was the thing we were trying to achieve initially.
You can either review our changes and point out what we missed in the migration process or you make a new PR with your migration in case you have fixed all the tests as well and have a more sophisticated solution at hand already.

**Comment by markus2330** [comment]
@Bushuo because of your request in [#1038](https://github.com/ElektraInitiative/PermaplanT/pull/1038#issuecomment-1856584847). I think it is faster for you if you simply make a new PR with your branch you talked about where you only do the vitest migration (and please update of docu: doc/tests/README.md and if possible also make a short writeup of choices in doc/decisions/frontend_unit_testing.md).
