### ISSUE TITLE
Adding SHA-Commit / Git Info to Frontend

### ISSUE THREAD

**Issue by lukashartl** [ElektraInitiative/PermaplanT#164]
In the very near future, we will have at least 3 different public instances of PermaplanT running (pr, dev, prod).

When accessing the frontends, the user has no idea which version of the application is currently being served on this domain name.

Maybe be should add some kind of git information. Like the sha commit id that has been built.

**Comment by markus2330** [comment]
Isn't it also clear from the logs what was deployed last? E.g. https://build.libelektra.org/job/permaplant/job/master/lastSuccessfulBuild/ should always say what is deployed on dev.permaplant.net? This information also should be in the documentation.

The only requirement so that previous question is true that deployment without being successful must be impossible. Is there a possibility for this to happen?

But adding the hash also shouldn't be a problem, if it is more convenient for someone. Only time shouldn't be added, as it the build wouldn't be reproducible anymore.

> prod

Is simply www.permaplant.net

This topic definitely will become relevant once non-devs start reporting bug. But then we maybe should directly add a feature to report a problem (which knows the SHA).

**Comment by markus2330** [comment]
Is incrementing the version numbers in frontend an alternative here?

**Comment by lukashartl** [comment]
> Is incrementing the version numbers in frontend an alternative here?

Yes! This might also fix #415
