### ISSUE TITLE
database features

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#26]
This summarizes features for the database that might be not relevant for the first version if we are able to introduce them later easily without loosing already entered seeds:

- [ ] multi-user database
- [x] ~~[Inheritance](https://www.postgresql.org/docs/current/ddl-inherit.html) for varieties from plants (so that common properties can be defined at one place), see below~~
- [x] #88
- [x] literature review+experience (if it was already planted in our garden) for plants (requires a field so that admins can review the varieties+seeds of other users)
- [x] #90
- [x] multi-language English+German (requires to have several rows for every text that could be translated, e.g. notes)
- [x] multi-user for varieties+seeds (requires that user is stored in the DB, so that users don't see not-yet-reviewed varieties and seeds from each other)

__*EDIT @aidnurs 10.03.2023:*__
- [x] #91

```mermaid
classDiagram

    class Family:::abstract {
      +Family[] buddy
      +Family[] dislike
    }
    class Subfamily:::abstract {
    }
    class Genus:::abstract {
    }
    class Species {
      +int height
      +int width
    }
    class Variety {
      +int height
      +int width
    }

    Species <|-- Variety
    Genus <|-- Species
    Subfamily <|-- Genus
    Family <|-- Subfamily

```

**Comment by markus2330** [comment]
@aidnurs @buenaflor we should also discuss which of these features are easier to be implemented within the scraper (and for which the database can be changed without a need to run the scraping scripts again).

**Comment by aidnurs** [comment]
Hey @markus2330 ,

regarding your latest comment above: you're right, PSQL Inheritance will not solve the challenges described above. I'll leave the main points from the [PSQL documentation](https://www.postgresql.org/docs/current/ddl-inherit.html) here:

> Inheritance does not automatically propagate data from INSERT or COPY commands to other tables in the inheritance hierarchy.

> All check constraints and not-null constraints on a parent table are automatically inherited by its children, unless explicitly specified otherwise with NO INHERIT clauses. Other types of constraints (unique, primary key, and foreign key constraints) are not inherited.

> Table inheritance is typically established when the child table is created, using the INHERITS clause of the CREATE TABLE statement.

So the inheritance is useful to deal with complex DDL structure on the startup, but will not help us to avoid bulk operations e.g. updating a column of the entire `genus`.

I would suggest proceeding with foreign keys and table relationships. In case of a conflict, I would prioritize the "deepest" entity in the hierarchy. As you described, when there is a height value in a species and in a variety, variety will win. 

In order to implement hierarchy relations, I would also use many-to-many tables having the same prioritization mechanism as described above.

I'll write this decision down in our documentation today

**Comment by markus2330** [comment]
@NurramoX the only remaining issue here is how to deal with concurrent access of different users working on the same map.
