### ISSUE TITLE
document backend architecture

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#294]
Should answers questions like:

    - Both `entity` and `dto` exists as file and directory in the `model` package.
      Shouldn't they both be a regular package of their own?
    - Both `entity` and `dto` split each struct and it's function implementations across two files.
      Wouldn't it make more sense to put struct and functions together into one file for each?
    - Why is `dto` part of the service layer?
      As this is the way we represent data in the api it fits better as subpackage of `controller`.
    - Intersection of layers.
      The service layer should be the one acting between controllers and database.
      Why do controllers get the database connection pool as argument when this would better fit the service layer?
      Why does the database layer handle mapping from entity to dto when this should belong in the service layer?

**Comment by kitzbergerg** [comment]
One thing we might want to consider is using traits instead of implementing e.g. entities themselves. So e.g. we could have a trait
```rust
trait Database {
    type T;
    fn find() -> Vec<Self::T>;
    fn find_by_id(id: i32) -> Self::T;
    fn create(element: Self::T) -> Self::T;
    fn delete(id: i32) -> Self::T;
}
impl Database for Plants {
    type T = Self;

    fn find() -> Vec<Self::T> {
        todo!()
    }

    fn find_by_id(id: i32) -> Self::T {
        todo!()
    }

    fn create(element: Self::T) -> Self::T {
        todo!()
    }

    fn delete(id: i32) -> Self::T {
        todo!()
    }
}
```
although that will require a lot of thinking (as we need async traits which is a separate library, we need to make the Database trait work for all different variants )

**Comment by kitzbergerg** [comment]
> - Both `entity` and `dto` exists as file and directory in the `model` package.
>   Shouldn't they both be a regular package of their own?

This is how you handle modules in Rust. You can either have a file called e.g. `entity.rs` and a directory `entity/` or you can have no such file, but then you are required to put a `mod.rs` inside the `entity/` directory.

> - Both `entity` and `dto` split each struct and it's function implementations across two files.
>   Wouldn't it make more sense to put struct and functions together into one file for each?

In the beginning I put them like this. This is because of the explanation in point 1. Although you don't have to do it like this. Most libraries put struct and impl in one file. I don't have a strong preference so whatever you prefer is fine.

> - Why is `dto` part of the service layer?
>   As this is the way we represent data in the api it fits better as subpackage of `controller`.

DTO is part of the `model` module. Generally DTOs should be allowed to 'live' in both controller and service layer (at least they taught us that in SEPM). Therefore I would leave it in model together with entity as those represent the data we act upon.
Also I don't quite understand why you mean DTO is part of the service layer. There folder `service/` represents the service layer and DTOs are not in there.

> - Intersection of layers.
>   The service layer should be the one acting between controllers and database.
>   Why do controllers get the database connection pool as argument when this would better fit the service layer?

This is how actix does it. We are not actually putting the pool there, but rather actix 'provides' the data. There is no other way of doing this apart from making a global pool and ignoring the way actix wants us to do 'data management' (or however you want to call it)

>   Why does the database layer handle mapping from entity to dto when this should belong in the service layer?

I agree this should be moved to either controller or service layer.

**Comment by kitzbergerg** [comment]
@markus2330 I wrote it in here for now. After discussion we can put the relevant parts in the documentation.

**Comment by markus2330** [comment]
> although that will require a lot of thinking

Better keep it simple.

> After discussion we can put the relevant parts in the documentation.

I don't know what you want to discuss here. Please create a PR with a proper description of how our architecture is (or should be if there are currently troubles, please create issues for such problems), as already asked of you several times and as written in your individual tasks.
