### ISSUE TITLE
plant search enhancements

### ISSUE THREAD

**Issue by kitzbergerg** [ElektraInitiative/PermaplanT#379]
The implementation of plant search (#258, #367) using `pg_trgm` makes it difficult to implement some features as described in the use case [search_plants](https://github.com/ElektraInitiative/PermaplanT/blob/master/doc/usecases/current/search_plants.md).

Missing features are:

- [ ] consider language when ranking (you can simply add ` * 0.5` to the end of similarity, e.g. `similarity(unique_name, search_query) * 0.5` to change the ranking)
- [ ] hierarchical search
- [ ] Search accuracy (stop words, stemming, etc.)  
      This is somewhat unnecessary when using `pg_trgm` as the fuzzy search is powerful enough to not require stemming (and stop words don't really occur in our search use-cases)

Before attempting to implement those feature it might be a good idea to have a look at alternative databases like [Meilisearch](https://www.meilisearch.com/) or [Elasticsearch](https://www.elastic.co/).

**Comment by markus2330** [comment]
We already agreed to remove `adding additional columns with extra syntax`, so I removed it in the top post, too.

For search accuracy I also thought we came to a conclusion that it is fine as-is?

Please fix the use case accordingly.

So the only remaining improvement would be the hierarchy (i.e. find tomatoes that do not have tomato in their name but are known to be a tomato because they belong to the species). Do you think that [Meilisearch](https://www.meilisearch.com/) or [Elasticsearch](https://www.elastic.co/)  could help in this regard?

But anyway, I think we can leave this feature as unimplemented for now. Please write it to notes in the use case (with a link to this issue).
