### ISSUE TITLE
implement SSE/observer pattern

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#393]
Part of plant use case, to be discussed today

**Comment by kitzbergerg** [comment]
@Bushuo Maybe link your PR here. If there then are question we can either discuss it here or in the PR.

**Comment by Bushuo** [comment]
@kitzbergerg I added my pull request, I still need a little more time to get it ready for review. But the backend structure will not change much anymore.
Of course, instead of the global vector, we will use a service and database, but it is still unclear to me how the tables will look, so I left it like this.

I will be adding a auth mechanism as well. @absurd-turtle and I discussed a flow like this:
1. User requests a short-lived token behind a auth guarded route GET `api/map_updates/token/{map_id}`
2. User connects to the SSE endpoint GET `api/map_updates/{token}`
3. Server validates the token and removes it

The server cleans all tokens after a certain amount of time.

The token has the following data associated with it that is saved in the database:
- map_id
- user_id
The combination of map_id and user_id is unique so each user can only be connected to a single map at a time.

**Comment by markus2330** [comment]
> it is still unclear to me how the tables will look

It is important that we finally clarify this. Can you please say (probably in a separate issue) what exactly in doc/database/schemata.md is unclear/missing/...?

> I will be adding an auth mechanism as well.

This can be done in a later PR, too. (And it is probably better, I think we were generally too fast with introducing auth everywhere. We don't even have documentation how to benchmark/do manual requests/...).

> User connects to the SSE endpoint GET api/map_updates/{token}

Please use api/sse/maps (or api/updates/maps if it is not restricted to be used with sse) to be confirming to API guidelines, see #403.

> The combination of map_id and user_id is unique so each user can only be connected to a single map at a time.

This is very restrictive, it should be possible for a user to have e.g. different maps in different tabs.

**Comment by Bushuo** [comment]
> Please use api/sse/maps (or api/updates/maps if it is not restricted to be used with sse) to be confirming to API guidelines, see https://github.com/ElektraInitiative/PermaplanT/pull/403.
>
Ok, I will use `api/updates/maps`.

> This is very restrictive, it should be possible for a user to have e.g. different maps in different tabs.
>
Ok, then a user can only connect once to each map. I will implement this in a separate PR. 

> It is important that we finally clarify this. Can you please say (probably in a separate issue) what exactly in doc/database/schemata.md is unclear/missing/...?
>
Ok, I will create an issue for it and make a suggestion.

**Comment by Bushuo** [comment]
@markus2330 I created two issues regarding the above 
SSE auth mechanism: #409 
Missing documentation for layer elements: #408
