### ISSUE TITLE
Nextcloud chat on landing page

### ISSUE THREAD

**Issue by absurd-turtle** [ElektraInitiative/PermaplanT#397]
- [ ] highlight items when hovering
  - [ ] group by date, show exact time (not 5 min ago)
    
Logged in users can:
  - [ ] give reactions to posts
    
Chat features (in order of importance)
  1. [ ] show images
  2. [ ] text should be mark/copyable
  3. [ ] emoji
  4. [ ] reactions
  5. [ ] files
  6. [ ] reply
  7. [ ] directly share photo (take photo with phone)
  8. [ ] remove msg/reaction

**Comment by absurd-turtle** [comment]
@markus2330 Please specify how the chat should look like and what functionality it should have

**Comment by markus2330** [comment]
We will look into it tomorrow. Do you have a feeling if either:

- https://www.npmjs.com/package/react-chat-elements
- https://www.freecodecamp.org/news/building-a-modern-chat-application-with-react-js-558896622194/

could be useful for you for development or design?

**Comment by absurd-turtle** [comment]
> We will look into it tomorrow. Do you have a feeling if either:
> 
>     * https://www.npmjs.com/package/react-chat-elements
> 
>     * https://www.freecodecamp.org/news/building-a-modern-chat-application-with-react-js-558896622194/
> 
> 
> could be useful for you for development or design?

The react-chat-elements look good to me. I'll check it out.

**Comment by markus2330** [comment]
I pushed the UC: [803c96f653dca61aa5898b86802ea074ce9d68f7](https://github.com/ElektraInitiative/PermaplanT/pull/424/commits/803c96f653dca61aa5898b86802ea074ce9d68f7)

Yvonne doesn't like the react-chat-elements so much (colors, shape of text messages, fonts, ...) and I also think that the look&feel of Nextcloud spreed is better. So we prefer if the look&feel&functionality closely resemble that of [Nextcloud spreed](https://cloud.permaplant.net/apps/spreed/), of course adapted so that it fits to permaplant.net

The first UC is nearly-completely read-only, only posting of reactions (by logged in people) should be allowed.

Please have a look at the UC and ask if anything is unclear. (I also added an idea about RSS, please answer in #2 if it is feasible).

**Comment by absurd-turtle** [comment]
It seems like we have to funnel the traffic for unauthenticated users over our backend.
While Nextcloud Spreed supports guests on principle, it looks like they don't accept requests which come from outside the Nextcloud application.
When I try to send a request to the Spreed chat endpoint 
e.g. 
```https://cloud.permaplant.net/ocs/v2.php/apps/spreed/api/v1/chat/i2ck2uyp?&lookIntoFuture=0```
it's response is:
```
{
    "message": "CSRF check failed"
}
```

**Comment by markus2330** [comment]
Actually, I think the backend as proxy for the chat functionality is better from architecture point of view anyway. That way we can use SSE instead of each frontend polling for new chat messages (and triggering the notification directly without Nextcloud). This is not really important for the landing page but important for many users working on maps.

How many Nextcloud chat API calls are there? How difficult would it be to make the whole chat via backend?

Or we make a hybrid version: only
1. the traffic of unauthenticated users and
2. the backend does the polling (notification via SSE).

But isn't this more effort in total?

**Comment by absurd-turtle** [comment]
I don't see how it would be better overall. The polling has to be done for each user either way. I don't know if it's better when the backend does the polling. For the frontend side it would be a bit more efficient in terms of data and total requests sent but I don't know if it is worth it.
In any case I haven't found a solution to send unauthenticated requests to Nextcloud directly, so at least this has to be funneled through the backend.

There are 12 endpoints for interacting with a existing conversation/chat.
The API is documented [here](https://nextcloud-talk.readthedocs.io/en/latest/chat/#get-mention-autocomplete-suggestions)

**Comment by markus2330** [comment]
Let us do this later, I unassigned you.
