### ISSUE TITLE
Get geo coordination

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#402]
@absurd-turtle @ThorbenStaufer What about allowing the user to select coordinates for the maps via a openstreetmap like we have on the landing page. Is this feasible?

**Comment by ThorbenStaufer** [comment]
It could work. Not ideal since a user potentially has to scroll through the entire map to get the right location, depending on their position relative to map center, but it is better than typing the coordinates manually. I need to test it in the code though, to verify that I haven't overlooked anything critical.

**Comment by markus2330** [comment]
> it is better than typing the coordinates manually

Definitely. And it might even be better than address lookup if you have a field/garden somewhere where are no houses nearby.

**Comment by ThorbenStaufer** [comment]
The location picker via OpenStreetMap/Leaflet works perfectly. I need to make some small adjustments with the map creation frontend but I should be able to open a PR soon on that.

**Comment by markus2330** [comment]
Great news! Let us again only load the component on click. Directly entering the coordinates is the alternative.

**Comment by markus2330** [comment]
@ThorbenStaufer is this done?

**Comment by ThorbenStaufer** [comment]
Not yet. The implementation still needs a small adjustment but it should be almost done. Also forgot to link the PR to this issue, which I will also correct.

**Comment by markus2330** [comment]
Fixed
