### ISSUE TITLE
Scraper to fetch plants data

### ISSUE THREAD

**Issue by aidnurs** [ElektraInitiative/PermaplanT#41]
As you know, the knowledge space of permaculture is huge, that's why we should be able to fetch and populate our database with plant information from available sources on demand. Since most of the web sources with such information are MVC based, we cannot easily access the raw data, so we should implement a smart web scraper that collects needed data by crawling through the source webpage.

TODOs:

- [x] implement web scraper
- [x] save as a file to a permanent folder
- [x] ~~process the files on the backend side~~
- [x] script to insert data into database
- [x] ~~update the `decisions` folder with the `scraper` section~~
- [x] update `README` in the scraper folder on how to use the service

Open questions: 
1. Which fields are actually needed? There are 2 types of pages on the source webpage: a listing of all plants available and a detail view of a single plant. While it is clear that we should fetch the entire list of plants, it is not obvious to me what fields playing the main role on a detail page

**_EDIT 04.02.2023 17:30:_**
TODOs:
- [x] Scrap "Propagation"
- [x] Scrap "Cultivation"
- [x] Scrap "Common name" available after the binomial name in the title
- [x] Remove "Imported References" columns from the schemata. (I don't think it's needed @markus2330?)
- [x] License??
- [x] Scrap "Last modified data"
- [x] Scrap "synonyms" OPTIONAL
- [x] Scrap "Has drought tolerance Intolerant"
- [x] Scrap "Tolerates wind"
- [x] Define ENUMs. backend or PSQL?

**Comment by markus2330** [comment]
> update the decisions folder with the scraper section

If we write a decision, it must come before the implementation. A decision here only makes sense if there are several good options (e.g. of scraper frameworks) available and you don't have a strong preference. But it looks like (#42) that you already decided?

practicalplants.org is quite broken and there is no indication that it will be repaired anytime soon. In particular Special:ExportRDF seems to be broken, and this probably would be the easiest accessible source of data? The last modified data is mostly 10 years and older. So everything looks like that this will be a one-time import. So in conclusion, you can simply use what gives you the fastest success and it is in this case not needed to write a decision about it, as it will be probably code that is only used once for initial import.

>  Which fields are actually needed?

All the information of the plants can be useful within PermaplanT, some information is only to be displayed to the user, e.g. Medicinal uses. If there are special problems in retrieving this data, we can also life without it.

See https://github.com/ElektraInitiative/PermaplanT/blob/master/doc/architecture/context.md for must-have entries.

> There are 2 types of pages on the source webpage: a listing of all plants available and a detail view of a single plant. While it is clear that we should fetch the entire list of plants, it is not obvious to me what fields playing the main role on a detail page

Very important is (examples are written in "quotes", I use https://practicalplants.org/wiki/solanum_lycopersicum/ if not noted otherwise):

- Latin name of species "*Solanum lycopersicum*"
- family "Solanaceae"
- English name of species: "Tomato"
- license "CC BY-SA"
- last modified date "04-05-2013"

Not so important/maybe redundant is:

- in some cases there are synonyms of English names, e.g. for https://practicalplants.org/wiki/solanum_sisymbriifolium/ there are 3 synonyms: "Sticky Nightshade",  "Litchi Tomato", "Morelle De Balbis"
- Everything in the "top bar" (Niche, Functions, ..., Cold&Heat) is very important[^1] and should be stored as enum

Everything not-duplicated of full data, in particular:

- environment
- Ecosystem Niche
- Root Zone Tendancy
- Mature Size

Everything not-duplicated in Facts, especially:

- article is incomplete yes/no
- Has drought tolerance Intolerant +
- soil preferences
- Tolerates wind

Very incomplete, so probably not worth getting:

- "Associations & Interactions", here plantbuddy.org has more/better data, is also licensed CC BY-SA, see https://github.com/serlo/PlantBuddies/issues/3#issuecomment-1405041405
- references

[^1]: The information in this top bar, however, seems to be redundant, and is probably the same as in full data and/or facts.

So probably it is best to write a prototype and see which information can be most easily retrieved in a form suitable for the database, what is redundant, which information is available for how many plants etc. Then we decide about a database schemata.

Please ask on any questions.

**Comment by aidnurs** [comment]
Thank you for the detailed answer @markus2330!

----

Hey @markus2330 @buenaflor,

Here are my latest notes and decisions regarding this task:

- Store data in files in csv format. I would like to keep the scraper independent from the backend and even from the data source, so the process can easily be adjusted in future if something changes in the architecture
- There are 2 parts of the process:
    1. scraper based on playwright library that stores the scraped data into files
    2. node script that connects to the database, processes the files and inserts the data
- I thought we could try to ask `practicalplants` to take their database over, since they don't maintain their webpage anymore (social medias as well since 2015). Since we develop in public, they would probably appreciate the initiative.

Another ideas for the project:
- set ids to negative numbers for the seed data, because in future, all migrations will get to the production with the seed data, which would mix with real data up and could potentially cause problems.

I'm still working on the task, there are still some small things to complete, however, you can already run the scraper and get the data on your local instance.

Sincerely,
Nursultan

**Comment by aidnurs** [comment]
@markus2330 

https://web.archive.org/web/20181219005150/https://practicalplants.org/wiki/Practical_Plants

Please check out the link above, it contains the backup version of the source webpage. There are also another snapshots of the webpage made during other time frames. This should solve our problem, could you check and advise the version i.e. snapshot date which is the closest for our needs

**Comment by markus2330** [comment]
> I thought we could try to ask practicalplants to take their database over

I already asked several times, via the official email address and directly to the initiator: no response so far.

> set ids to negative numbers for the seed data, because in future, all migrations will get to the production with the seed data, which would mix with real data up and could potentially cause problems.

The (reviewed) initial import can already be considered as real data. We have a test machine anyway (dev.permaplant.net vs. www.permaplant.net).

> https://web.archive.org/web/20181219005150/https://practicalplants.org/wiki/Practical_Plants

We checked two very common plants (garlic and tomato), they had the same last modified ~2013. So probably not so much happened after the initiation of practical plants? The archive seems to be much slower to scrap?

> could you check

Could you add the csv in the PR?

**Comment by markus2330** [comment]
> Remove "Imported References" columns from the schemata. (I don't think it's needed @markus2330?)

The citation marks (e.g. `[12][5][13][14][15][16]`) alone do not make sense, we also need the references. It is not really needed for PermaplanT but as practicalplants.org probably will never be revived, it would be a pity if this information gets lost.

> License??

Is in the bottom-right. Or do you think everything has CC BY-SA? https://practicalplants.org/wiki/practicalplants:copyrights/ indicates  that there also could be non-commercial?

> Scrap "synonyms" OPTIONAL
> Scrap "Has drought tolerance Intolerant"
> Scrap "Tolerates wind"
> Define ENUMs. backend or PSQL?

**Comment by aidnurs** [comment]
Hey @markus2330,

I've found a full archive of the practicalplants article:

1. https://github.com/practicalplants
     a. I've forked the repo for the case if they make it private again, which will not happen in my opinion. Let's fork it to our organization as well. https://github.com/aidnurs/archive.org-recovery
2. While you can find HTML files of each plant under the link above, here is a better link with all the data in XML format(weird structure but still good enough for our purposes). https://archive.org/details/wiki-practicalplantsorg_w

I think since we have all the data in the text formats either HTML or XML, we don't even need our web scrapper anymore. The thing we need is a processing script, which I'm going to focus on in the next couple of days. Of course, I'm waiting for your response first for better coordination. Let me know what do you think! In the meantime, I'm taking a look at new sources

Thanks,
Nursultan

**Comment by markus2330** [comment]
> I've found complete archives of the practicalplants articles:

Amazing, perfect! This takes care of all the timeout problems... :rocket: 

> https://github.com/aidnurs/archive.org-recovery

I forked it: https://github.com/ElektraInitiative/archive.org-recovery

> I suggest we proceed with Option 1, where we will process the HTML files of an article.

As it is easier for you.

> I'm not sure if we would like to have it in our mono repo [...]  ~500 mb

Agree, data outside of our repo but the scripts should be all in our repo (so that they are consistent with database schema etc.). Please also add CSV-files in the data repo. Please only use the ElektraInitiative repos.

Please create PR for parser (instead of scraper #42). Please read&fix comments about database schemata (which are basically all of them :wink:)

**Comment by markus2330** [comment]
EDIT: I renamed/recreated the repo, it is now called: https://github.com/ElektraInitiative/practicalplants

**Comment by aidnurs** [comment]
The issue is complete and can be closed after merging #48
