### ISSUE TITLE
doc/backend/01setup.md doesn't work

### ISSUE THREAD

**Issue by absurd-turtle** [ElektraInitiative/PermaplanT#437]
## Steps to Reproduce the Problem

- checkout master
- run migrations
- build backend

## Expected Result

backend starts

## Actual Result

latest migration can't be executed

## System Information

- PermaplanT: master
- Operating System: Linux

## Further Log Files and Output

To fix this I installed the postgis package
and executed the content of the latest migration manually with the postgres user:
CREATE EXTENSION IF NOT EXISTS postgis;

The problem seems to be that the permaplant user doesn't have the correct privileges to install the extension.
Please change the documentation to match the new installation process and fix the issue with the missing privileges.

**Comment by markus2330** [comment]
Thank you for reporting the issue! I fully agree that this is an urgent and important task.

In step 1 something like `GRANT ALL PRIVILEGES ON DATABASE permaplant TO permaplant;` is needed. This would obviously not be minimal permissions, but it might be okay for develop machines, as they also want `diesel database reset` to work.

There is also another problem, the 01setup.md also has steps intermixed that are actually to run the backend (step 3 and step 7, and of course "Test server using Swagger"), imho they should be extracted to 02run.md (and the other numbers moved further along).

**Comment by markus2330** [comment]
I hope Christoph can fix these issues and recheck if the whole setup procedure really works.

**Comment by temmey** [comment]
Currently, multiple documentation pages located in different places are required to get the system up and running.
/doc/backend/01setup.html
/doc/backend/index.html
/doc/setups/index.html
/doc/setups/keycloak/index.html
/doc/setups/nextcloud/index.html
/doc/setups/nginx/index.html
/doc/development_setup.html
/frontend/README.md

I suggest the following structure for the document:
prepare keycloak (container) (/doc/setup/keycloak)
prepare nextcloud (container) (/doc/setup/nextcloud)
install backend (cli) + postgis container (/doc/setup/backend)
install frontend (cli) (/doc/setup/frontend)

**Comment by temmey** [comment]
At present, the development setup utilizes a mix of services.
For instance:
nextcloud https://cloud.permaplant.net
keycloak https://auth.permaplant.net/realms/PermaplanT/.well-known/openid-configuration

Is this the expected approach? What happens if developers outside the project team want to work on the app, but one or both of these services are offline?

In my opinion, it would be more practical to use local instances (assisted by Docker) for a development environment. Additionally, we could create a separate section in the documentation detailing how to set up permaplant for production.
What do you think @markus2330 ?

**Comment by markus2330** [comment]
> I suggest the following structure for the document:

I don't think we should try to move everything related to setup on one place because not every setup is needed by everyone. Especially not everyone wants to setup Keycloak or Nextcloud (but instead decide to simply use ours).

Instead we should simply link all these setups from one point and give general statements if and when these instructions need to be followed.

What we should make more consistent is the style and completeness of the setup tutorials. We also should be careful not to repeat too much information, e.g. version information is better on a single place.

> Is this the expected approach?

Yes, e.g. Nextcloud you would only install if you need to reconfigure Nextcloud or read administrative logs. But even in such cases you can ask and we try our best to do these reconfigurations or give you access as needed so that you develop using our instances.

> What happens if developers outside the project team want to work on the app, but one or both of these services are offline?

As they are essential for us, too, we try to keep them always up and running. We didn't have any downtime up to now. Furthermore, we want to improve high availability even more.

> What do you think @markus2330 ?

For a start it is best to (in this order):

1. solve this specific issue (fix the one setup)
2. create an overview of setups+descriptions if you need to do this specific setup
3. reduce duplication
4. improve style etc.

I created #458 for 2-4. For npm versions we already have #395.

**Comment by markus2330** [comment]
It is enough to promote it at one point (probably also in  doc/setups/README.md as recommended it #458), it is up to everyone what to use and we should document at one point how do it manually.

Directly in fronend and backend README we should have a more declarative style (what is required) and then in the setups we can have a more howto style (but these changes I would also rather see in #458).

**Comment by temmey** [comment]
I don't have the needed permissions to make a new branch for a Pull Request. Could you please add me?

**Comment by markus2330** [comment]
>  diesel database reset

`GRANT ALL PRIVILEGES ON DATABASE permaplant TO permaplant;` doesn't work, it yields the error `"must be owner of database"`.  So it is not useful to recommend that command.

**Comment by 4ydan** [comment]
Do the new makefiles and .devcontainer help to resolve this issue? Can we still reproduce this or is this to be closed. Usually when `POSTGRES_USER` and `POSTGRES_PASSWORD` is set correct, you should be able to run migrations, no?

**Comment by markus2330** [comment]
> Usually if you setup your db correctly and when POSTGRES_USER and POSTGRES_PASSWORD is set correct, you should be able to run migrations, no?

If set "correctly" of course, but not every POSTGRES_USER has the permissions. So this issue is basically about giving the correct permissions so that

1. the migrations can successfully run
2. database can be reset (dev only feature)

1 and 2 need different permissions.

> Maybe we should add a section on how to setup the database if you are not using a container.

Exactly. We should be also transparent what the containers do.

**Comment by temmey** [comment]
> > diesel database reset
> 
> `GRANT ALL PRIVILEGES ON DATABASE permaplant TO permaplant;` doesn't work, it yields the error `"must be owner of database"`. So it is not useful to recommend that command.

In PostgreSQL, extensions are installed in 'schemas', not 'databases'. So, changing who owns a database won't affect this. To install an extension, a user needs to be a 'superuser', and our 'permaplant' user isn't one.

We could remove the command 'CREATE EXTENSION postgis' from our up.sql file and only include it in our backup setup guide. However, since we often add new extensions for development, this might not be the best approach.

It's worth noting that the PostGIS Docker image makes the user a 'superuser'.

We could think about adding the command 'ALTER USER permaplant WITH SUPERUSER;' which would work fine in a development environment. However, I wouldn't recommend using it in a production setting as it could pose security risks.

**Comment by markus2330** [comment]
@temmey thanks for the write-up! I think exactly a text like this should be in our documentation. I agree that the SUPERUSER is only for dev.
