### ISSUE TITLE
typeshare command different in CI vs. docu

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#440]
In our README we recommend to run `npm run generate-api-types` in the frontend but the CI uses `typeshare ./ --lang=typescript --output-file=../frontend/src/bindings/definitions.ts` in ci/build-scripts/build-backend.sh (ergo already while building the backend).

@lukashartl was this needed/on purpose?

Is there actually a reason why `npm run build` (or `npm run dev`) in the frontend doesn't call `npm run generate-api-types`?

**Comment by markus2330** [comment]
Probably this can be fixed together with #355, it definitely needs to be considered.

**Comment by lukashartl** [comment]
There is a reason for that:

`typeshare` is written in Rust. So the only dependency is having the rust toolchain. If we want to execute `typeshare` via `npm` we actually also need the nodejs toolchain.

https://github.com/ElektraInitiative/PermaplanT/blob/5b63db2f5f0f1f25e5754eef3be8ec9996db2d61/frontend/package.json#L10

When designing the pipeline I wanted to separate frontend and backend tasks into separate small images (one for `node` and one for `rust`), instead of using a big `rust+node` image.

Of course we could also add a big `rust+node` image as well, but I see no actual benefit.
