### ISSUE TITLE
Read-Only Offline Mode For Plant Layer

### ISSUE THREAD

**Issue by Bushuo** [ElektraInitiative/PermaplanT#445]
- [ ] connected/offline does not work: you can do plantings despite being offline (no connection to backend)
- [ ] repeated "Hello ..." only when online again

_Originally posted by @markus2330 in https://github.com/ElektraInitiative/PermaplanT/issues/436#issuecomment-1585731358_

**Comment by markus2330** [comment]
Currently "Hello ..." is emitted arbitrarily. It should be only said again when the online state actually changes (e.g. got online again or switched to read-only). I added this above.

**Comment by Bushuo** [comment]
@markus2330 
I have a question about this feature.
How should the read only mode work?
Should it be generally possible to click on stuff and view the map in a read only state (i.e. everything where network interaction is not needed should work)
Another possibility is to block all pointer events, but then nothing works until the network is there again.

**Comment by markus2330** [comment]
Ideally, a user could look at everything except what was never fetched and it should be transparent what was not fetched yet. I.e. switching between layers and years should be possible. (Actually the same for non-read-only edit mode.)

But the details are to be researched by you. So the goal for now is that you implement what is easy to be implemented and write in the thesis about what is possible, so that we can later decide what we actually do. If you don't want to have your thesis so theoretical, we can also find another approach (e.g. that you more describe what worked as a feasibility study).

For this issue to be resolved it is better that less works but it works flawlessly.

**Comment by markus2330** [comment]
What is the current status? How can we bring this to a quick end? Let us keep this minimal, fixes like #727 are much more important in the current state of PermaplanT.

**Comment by markus2330** [comment]
Further clarification: The main goal is to prevent data loss. The offline/disconnected user (including when the server restarts) should not lose much more than one click worth of data, then PermaplanT should switch to read-only and further actions should be prevented. (It must be clear that no action can be done now).

That pressing F5 and/or a new login is necessary is not a problem.

Avoiding spam like:

![image](https://github.com/ElektraInitiative/PermaplanT/assets/7949075/caf1af28-6ebb-4099-906c-f3682d7e95b5)

is nice to have.
