### ISSUE TITLE
smoke test

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#607]
### Tasks

Create a minimal test that should check if the map loads to avoid #504.

### Use case

plants_layer

### Related Pull request

#504

**Comment by 4ydan** [comment]
I think we might need docker-compose inside Jenkins.
We need a new stage now for the frontend tests, where we start 4 containers in total.
- frontend
- backend
- database
- and the container that performs the http calls

I think this will also require the caching to be functional, otherwise this stage will take another 10-15 extra minutes.
A cheap alternative would be to perform the tests on an already deployed website.
Or we dont integrate them yet at all in the pipeline.

**Comment by markus2330** [comment]
> I guess I found a solution that is not the best, but it will do the job I guess.

Which one?

And why not run the tests on `pr.permaplant.net`, it always gets a fresh database.

**Comment by 4ydan** [comment]
What if some other jenkins job overrides the page on pr.permaplant.net

**Comment by markus2330** [comment]
> What if some other jenkins job overrides the page on pr.permaplant.net

This shouldn't be a problem as it will be after the E2E already finished. I think this is the best and most realistic option (it contains all plants etc. Bugs might be only present with the full data set.)

**Comment by 4ydan** [comment]
I like the idea, I'm not sure if I fully understand it yet.
