### ISSUE TITLE
Heatmap Test Protocol

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#650]
I think we all have small misunderstandings about the manual test protocol, I hope I can clear this up on tuesday.
@markus2330 @kitzbergerg 

Manual tests should also be executable without the need of such a big json string. If every test requires that, we will have a hundred page long test protocol. Additionally the terminal should not be necessary for them to be performed. This increases the duration to perform the test.

[This](https://github.com/ElektraInitiative/PermaplanT/issues/640#:~:text=The%20general%20idea,the%20process%20clearer.)

**Comment by 4ydan** [comment]
I see it is an actual issue, that we need to manually add companions, neutral and antagonist to the db in order to perform this tests. The steps should be written in a way were they are already in the db.

**Comment by markus2330** [comment]
> I think we all have small misunderstandings about the manual test protocol, I hope I can clear this up on tuesday.

Yes, let us talk about this on Tuesday. To start the discussion: imho there are two different kinds of test protocols: one to show that a use case was done and another one for releases. In the long term most of it hopefully gets automatically tested. So imho the test protocols are mainly for:

- that devs show me what I can expect from PRs/implemented UCs
- steps to be automated later

To actually do all these tests manually will hopefully be only needed in the very first releases (for the user studies/beta tests).

> I see it is an actual issue, that we need to manually add companions, neutral and antagonist to the db in order to perform this tests. The steps should be written in a way were they are already in the db.

Yes, I also think that tests should simply import everything via scraper.

In the heatmap this was probably only done this way because the scraper for relations was not merged yet.
