### ISSUE TITLE
allow cancel of aborting tour

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#738]
### Describe the Bug

as we saw in the user study, people press on the x and want the tour back

### Steps to Reproduce the Problem

press x

### Expected Result

There should be a confirmation dialog with 3 options:

- continue tour
- restart tour next time
- disable this tour for me

### Actual Result

no possibility to continue the tour

### PermaplanT version

master

### Operating System

Linux

### Browser

Firefox

**Comment by ThorbenStaufer** [comment]
> there should be a "continue tour" button in the toolbar

I don't think it belongs into the toolbar, as this entire button would become obsolete the second the user completes the tour.
It rather belongs into a user settings page, which we sooner or later should have anyways.

> it should continue where the tour was quit

That would require to save the entire step either in local storage or the database.
This is rather a completely new feature than a simple bug fix.

In my opinion, I don't think this proposed fix resolves the underlying issue that we observed during the user study.
The main problem was, that the users did not know exactly what the cancel button would do.
A better solution would be to let the users confirm the cancellation of the tour and provide a dedicated place for re-enabling the tour.

A cancel confirmation was previously attempted to implement, but was not possible at that time due to an interaction with browser history navigation stated in #711.
Since the bug from #711 is now fixed thanks to #730, it could be possible that a confirmation on tour cancel is now feasible too.

**Comment by markus2330** [comment]
> I don't think it belongs into the toolbar, as this entire button would become obsolete the second the user completes the tour.
> It rather belongs into a user settings page, which we sooner or later should have anyways.

For simple continuation I agree. But if you are allowed to click to some component, the toolbar makes sense.

Imho settings is also not the right place and something related to #742 also not.

> This is rather a completely new feature than a simple bug fix.

Ok.

> A better solution would be to let the users confirm the cancellation of the tour

I am not a big fan of such confirmations. Some way to undo is imho the better approach. It is valid to quit and to continue later.

> and provide a dedicated place for re-enabling the tour.

Isn't that a completely new feature, too?

>   if the tour was already completed, the user should be able to click on a component of the map editor and can rerun the tour of that component

Either I missed something or you didn't comment on if it is possible to click on a component and get part of the tour related to the component? I think this would fit best to the working style of the last participant.

**Comment by ThorbenStaufer** [comment]
> But if you are allowed to click to some component, the toolbar makes sense.

That I agree with. My comment was purely on the "continuation from the last step".

> Isn't that a completely new feature, too?

I never said it wasn't. My comment was related to the fact that this issue is listed as a bug but the implementation of something like that needs more time and effort than simply fixing something. Time I do not have.

> Either I missed something or you didn't comment on if it is possible to click on a component and get part of the tour related to the component?

It is possible, but not trivial. We'd have to define onClick events for every target component of the tour steps, map their `data-tourid` to the respective tour step id, restart the tour and jump to the associated step. If we want to only show that specific step and not the entire tour from that point onward, we also need to update the step list during run time. On top of that, we need to add additional logic so that the frontend doesn't try to gain the completion Blossom again. That doesn't include the list of potential bugs that could appear, since the interactions between the tour and React are very fragile.

**Comment by markus2330** [comment]
Ok, then let us do a confirmation after clicking "x" of the tour with 3 options:

- continue tour
- restart tour next time
- disable this tour for me
