### ISSUE TITLE
Canvas resolutions

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#763]
### Describe the Bug

Shouldnt the canvas only be in the middle of the whole page? I would like to take screenshots of exactly the canvas size and compare them in tests, might need to resize the canvas for that so that I can get the exact sizes of the canvas for that and not have other stuff in my screenshots.

Ah I guess this is because you can shrink the other tool areas?

Edit: 
I see, I could use the divs above the canvas.
We can close this issue if its no real issue for you.

### Steps to Reproduce the Problem

Open the webapp, go to a map, open the dev window.

### Expected Result

Be exactly in the middle

### Actual Result

Going a bit too far right and down

### PermaplanT version

[permaplant.net](https://www.permaplant.net)

### Operating System

Windows 10

### Browser

Opera

### Additional info/logs

![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/b064c971-2d2d-426b-b6ed-d973c75a2c8f)

**Comment by markus2330** [comment]
If this is about taking the screenshot, maybe screenshot is not necessary for now, see https://github.com/ElektraInitiative/PermaplanT/pull/760#issuecomment-1663291583

We still should nevertheless look into the canvas, maybe we render something which is never shown because of this overlap. @Bushuo @absurd-turtle do you know something about this issue described here? Is it something worth fixing besides the need for tests?
